<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#14251a"><meta name="description" content="Experience Dinaledi Leisure Resort — weddings, pools and accommodation in Makgakgapatse Village, Giyani."><title>Dinaledi Leisure Resort | A Day Together</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Playfair+Display:ital,wght@0,500;1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="experience.css"></head>
<body><header><a class="logo" href="#" data-go="0"><i>✦</i><span>Dinaledi<small>Leisure Resort</small></span></a><p>Makgakgapatse Village · Giyani</p><button class="menu-button" aria-label="Open experiences"><i></i><i></i></button></header>
<nav class="menu-panel"><p>Choose an experience</p><button data-go="0">Welcome</button><button data-go="1">Swim</button><button data-go="2">Celebrate</button><button data-go="3">Stay</button><button data-go="4">Visit</button></nav>
<main><div class="track" id="track">
  <section class="scene welcome"><div class="welcome-grid" aria-hidden="true"><i></i><i></i><i></i><i></i></div><div class="shade"></div><div class="copy"><p class="eyebrow">Your day at Dinaledi</p><h1>Come as you are.<br>Leave with <em>stories.</em></h1><p>Swim, celebrate, sleep over—and experience a place built around being together.</p><button class="action" data-next>Begin the day <span>→</span></button></div><p class="gesture">Scroll or swipe to explore <b>→</b></p></section>
  <section class="scene swim"><div class="pool-photo"></div><div class="pool-tint"></div><div class="copy"><p class="eyebrow">01 — Swim</p><h2>Make your<br>own <em>waves.</em></h2><p>Touch the water. Warm Limpopo afternoons are better when everyone jumps in.</p><a class="action" href="tel:0769991323">Ask about pool visits <span>↗</span></a></div><div class="ripple-zone" aria-label="Touch to make water ripples"><span>Touch the pool</span></div></section>
  <section class="scene celebrate"><div class="celebrate-bg"></div><div class="shade"></div><div class="copy"><p class="eyebrow">02 — Celebrate</p><h2>Gather the<br><em>good times.</em></h2><p>Move the memories around. Weddings, music and the people who make the occasion yours.</p><a class="action" href="tel:0769991323">Plan your celebration <span>↗</span></a></div><div class="memory-board" aria-label="Move the celebration photographs"><figure class="card c1"><img src="images/unnamed (28).jpg" alt="Wedding at Dinaledi"><figcaption>The big day</figcaption></figure><figure class="card c2"><img src="images/unnamed (29).jpg" alt="Guests at Dinaledi"><figcaption>Dress for it</figcaption></figure><figure class="card c3"><img src="images/unnamed (15).jpg" alt="Celebration crowd"><figcaption>Everyone together</figcaption></figure><figure class="card c4"><img src="images/unnamed (32).jpg" alt="Friends celebrating"><figcaption>Your people</figcaption></figure></div></section>
  <section class="scene stay" id="stay"><div class="day-photo"></div><div class="night-photo"></div><div class="night-sky"></div><div class="shade"></div><div class="copy"><p class="eyebrow">03 — Stay</p><h2>Let the day<br>turn into <em>night.</em></h2><p>Drag the sun towards evening, then stay over at Dinaledi.</p><a class="action" href="tel:0769991323">Check accommodation <span>↗</span></a></div><div class="time-control"><span>Day</span><input id="sunset" type="range" min="0" max="100" value="20" aria-label="Change from day to night"><span>Stars</span><small>Drag the sunset</small></div></section>
  <section class="scene visit"><div class="visit-photo"></div><div class="shade"></div><div class="visit-copy"><p class="eyebrow">04 — Your turn</p><h2>Choose your<br><em>Dinaledi day.</em></h2><p>Makgakgapatse Village, R81, Giyani, 0826</p><div class="links"><a href="tel:0769991323"><small>Call</small>076 999 1323 <b>↗</b></a><a href="https://www.google.com/maps/search/?api=1&query=Dinaledi+Leisure+Resort+Giyani" target="_blank" rel="noopener"><small>Directions</small>Open Google Maps <b>↗</b></a><a href="https://www.tiktok.com/@dinaledi54" target="_blank" rel="noopener"><small>Follow</small>@dinaledi54 <b>↗</b></a></div></div></section>
</div></main>
<div class="progress"><span id="current">01</span><i><b id="bar"></b></i><span>05</span><p id="label">Welcome</p></div><button class="previous" aria-label="Previous experience">←</button><button class="next" aria-label="Next experience">→</button><script src="experience.js"></script></body></html>
